name: Setup EWS CI Environment
description: Configure uv, Python, and GitLab Package Registry for EWS packages

inputs:
  python-version:
    description: Python version to install
    required: false
    default: "3.12"
  gitlab-token:
    description: GitLab API token for package registry access
    required: true
  gitlab-project-id:
    description: GitLab project ID for package registry
    required: false
    default: "75984310"
  install-dependencies:
    description: Run uv sync to install dependencies
    required: false
    default: "true"
  setup-ews-config:
    description: Create ~/.config/ews/*.toml for packages that need auth (auto-detects from environment)
    required: false
    default: "true"
  ews-credentials:
    description: 'JSON object with all EWS credentials (e.g., {"github_token": "ghp_...", "gitlab_api_token": "glpat-...", "gitlab_api_read_token": "glpat-...", "gitlab_package_registry_url": "https://...", "ammonit_or_password": "...", "windcube_insights_password": "..."}). If provided, takes precedence over environment variables.'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Setup uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true

    - name: Install Python
      shell: bash
      run: uv python install ${{ inputs.python-version }}

    - name: Setup EWS config for EWS packages
      if: inputs.setup-ews-config == 'true'
      shell: bash
      env:
        EWS_CREDENTIALS: ${{ inputs.ews-credentials }}
      run: |
        mkdir -p ~/.config/ews/dataset_registries
        mkdir -p ~/.config/ews/config
        
        # Parse JSON credentials if provided
        if [ -n "${EWS_CREDENTIALS}" ]; then
          echo "ðŸ“¦ Parsing EWS credentials from JSON..."
          
          # Extract credentials using jq (available in GitHub runners)
          GITHUB_TOKEN_JSON=$(echo "$EWS_CREDENTIALS" | jq -r '.github_token // empty')
          GITLAB_API_TOKEN_JSON=$(echo "$EWS_CREDENTIALS" | jq -r '.gitlab_api_token // empty')
          GITLAB_API_READ_TOKEN_JSON=$(echo "$EWS_CREDENTIALS" | jq -r '.gitlab_api_read_token // empty')
          GITLAB_PACKAGE_REGISTRY_URL_JSON=$(echo "$EWS_CREDENTIALS" | jq -r '.gitlab_package_registry_url // empty')
          AMMONIT_OR_PASSWORD_JSON=$(echo "$EWS_CREDENTIALS" | jq -r '.ammonit_or_password // empty')
          WINDCUBE_INSIGHTS_PASSWORD_JSON=$(echo "$EWS_CREDENTIALS" | jq -r '.windcube_insights_password // empty')
          
          # Use JSON values if provided, otherwise fall back to environment variables
          GITHUB_TOKEN="${GITHUB_TOKEN_JSON:-${GITHUB_TOKEN:-}}"
          GITLAB_API_TOKEN="${GITLAB_API_TOKEN_JSON:-${GITLAB_API_TOKEN:-}}"
          GITLAB_API_READ_TOKEN="${GITLAB_API_READ_TOKEN_JSON:-${GITLAB_API_READ_TOKEN:-}}"
          GITLAB_PACKAGE_REGISTRY_URL="${GITLAB_PACKAGE_REGISTRY_URL_JSON:-${GITLAB_PACKAGE_REGISTRY_URL:-}}"
          AMMONIT_OR_PASSWORD="${AMMONIT_OR_PASSWORD_JSON:-${AMMONIT_OR_PASSWORD:-}}"
          WINDCUBE_INSIGHTS_PASSWORD="${WINDCUBE_INSIGHTS_PASSWORD_JSON:-${WINDCUBE_INSIGHTS_PASSWORD:-}}"
          
          echo "âœ… Credentials loaded from JSON"
        else
          echo "ðŸ“¦ Using environment variables for credentials..."
          # Use environment variables directly
          GITHUB_TOKEN="${GITHUB_TOKEN:-}"
          GITLAB_API_TOKEN="${GITLAB_API_TOKEN:-}"
          GITLAB_API_READ_TOKEN="${GITLAB_API_READ_TOKEN:-}"
          GITLAB_PACKAGE_REGISTRY_URL="${GITLAB_PACKAGE_REGISTRY_URL:-}"
          AMMONIT_OR_PASSWORD="${AMMONIT_OR_PASSWORD:-}"
          WINDCUBE_INSIGHTS_PASSWORD="${WINDCUBE_INSIGHTS_PASSWORD:-}"
        fi
        
        # GitHub token
        if [ -n "${GITHUB_TOKEN}" ]; then
          cat > ~/.config/ews/config/github.toml <<EOF
        [github]
        username = "${{ github.actor }}"
        email = "noreply@ews-consulting.com"
        token = "${GITHUB_TOKEN}"
        EOF
          chmod 600 ~/.config/ews/config/github.toml
          echo "âœ… Created ~/.config/ews/config/github.toml"
        else
          echo "âš ï¸  No GitHub token available, skipping config creation"
        fi
        
        # GitLab tokens (for .pypirc)
        if [ -n "${GITLAB_API_TOKEN}" ] || [ -n "${GITLAB_API_READ_TOKEN}" ]; then
          GITLAB_URL="${GITLAB_PACKAGE_REGISTRY_URL:-https://gitlab.com/api/v4/projects/75984310/packages/pypi}"
          
          cat > ~/.pypirc <<EOF
        [distutils]
        index-servers =
            gitlab
        
        [gitlab]
        repository = ${GITLAB_URL}
        username = __token__
        password = ${GITLAB_API_TOKEN:-${GITLAB_API_READ_TOKEN}}
        EOF
          chmod 600 ~/.pypirc
          echo "âœ… Created ~/.pypirc for GitLab Package Registry"
        else
          echo "â„¹ï¸  No GitLab tokens available, skipping .pypirc creation"
        fi
        
        # Ammonit-OR password
        if [ -n "${AMMONIT_OR_PASSWORD}" ]; then
          cat > ~/.config/ews/config/ammonit-or.toml <<EOF
        [ammonit-or]
        email = "wm@ews-consulting.com"
        password = "${AMMONIT_OR_PASSWORD}"
        EOF
          chmod 600 ~/.config/ews/config/ammonit-or.toml
          echo "âœ… Created ~/.config/ews/config/ammonit-or.toml"
        else
          echo "â„¹ï¸  No Ammonit OR password available, skipping config creation"
        fi
        
        # Windcube Insights password
        if [ -n "${WINDCUBE_INSIGHTS_PASSWORD}" ]; then
          cat > ~/.config/ews/config/windcube-insights.toml <<EOF
        [windcube-insights]
        email = "wm@ews-consulting.at"
        password = "${WINDCUBE_INSIGHTS_PASSWORD}"
        EOF
          chmod 600 ~/.config/ews/config/windcube-insights.toml
          echo "âœ… Created ~/.config/ews/config/windcube-insights.toml"
        else
          echo "â„¹ï¸  No Windcube Insights password available, skipping config creation"
        fi

        # Compatibility with old tests (we transitioned to ~/.config/ews/config like /etc/ews/config)
        if ls ~/.config/ews/config/*.toml 1> /dev/null 2>&1; then
          cp ~/.config/ews/config/*.toml ~/.config/ews/
        fi

    - name: Setup GitLab Package Registry
      uses: EWS-Consulting-Public/setup-uv-gitlab-registry-action@v1
      with:
        token: ${{ inputs.gitlab-token }}
        project-id: ${{ inputs.gitlab-project-id }}

    - name: Install dependencies
      if: inputs.install-dependencies == 'true'
      shell: bash
      run: |
        if [ -f uv.lock ]; then
          echo "ðŸ“¦ Using committed uv.lock"
          uv sync --frozen --all-extras
        else
          echo "ðŸ“¦ No uv.lock found, generating..."
          uv sync --all-extras
        fi
