name: Setup EWS CI Environment
description: Configure uv, Python, and GitLab Package Registry for EWS packages

inputs:
  python-version:
    description: Python version to install
    required: false
    default: "3.12"
  gitlab-token:
    description: GitLab API token for package registry access
    required: true
  gitlab-project-id:
    description: GitLab project ID for package registry
    required: false
    default: "75984310"
  install-dependencies:
    description: Run uv sync to install dependencies
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - name: Setup uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true

    - name: Install Python
      shell: bash
      run: uv python install ${{ inputs.python-version }}

    - name: Setup GitLab Package Registry
      uses: EWS-Consulting-Public/setup-uv-gitlab-registry-action@v1
      with:
        token: ${{ inputs.gitlab-token }}
        project-id: ${{ inputs.gitlab-project-id }}

    - name: Install dependencies
      if: inputs.install-dependencies == 'true'
      shell: bash
      run: |
        if [ -f uv.lock ]; then
          echo "📦 Using committed uv.lock"
          uv sync --frozen --all-extras
        else
          echo "📦 No uv.lock found, generating..."
          uv sync --all-extras
        fi
