name: Setup EWS CI Environment
description: Configure uv, Python, and GitLab Package Registry for EWS packages

inputs:
  python-version:
    description: Python version to install
    required: false
    default: "3.12"
  gitlab-token:
    description: GitLab API token for package registry access
    required: true
  gitlab-project-id:
    description: GitLab project ID for package registry
    required: false
    default: "75984310"
  install-dependencies:
    description: Run uv sync to install dependencies
    required: false
    default: "true"
  setup-ews-config:
    description: Create ~/.config/ews/*.toml for packages that need auth (auto-detects from environment)
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - name: Setup uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true

    - name: Install Python
      shell: bash
      run: uv python install ${{ inputs.python-version }}

    - name: Setup EWS config for EWS packages
      if: inputs.setup-ews-config == 'true'
      shell: bash
      run: |
        mkdir -p ~/.config/ews/dataset_registries
        mkdir -p ~/.config/ews/config
        
        # Auto-detect credentials from environment (set via 'secrets: inherit')
        # Repository secrets are automatically available as environment variables
        
        # GitHub token (GITHUB_TOKEN is always available in GitHub Actions)
        if [ -n "${GITHUB_TOKEN}" ]; then
          cat > ~/.config/ews/config/github.toml <<EOF
        [github]
        username = "${{ github.actor }}"
        email = "noreply@ews-consulting.com"
        token = "${GITHUB_TOKEN}"
        EOF
          chmod 600 ~/.config/ews/config/github.toml
          echo "âœ… Created ~/.config/ews/config/github.toml"
        else
          echo "âš ï¸  No GitHub token available, skipping config creation"
        fi
        
        # Ammonit-OR password (from repository secret AMMONIT_OR_PASSWORD)
        if [ -n "${AMMONIT_OR_PASSWORD:-}" ]; then
          cat > ~/.config/ews/config/ammonit-or.toml <<EOF
        [ammonit-or]
        email = "wm@ews-consulting.com"
        password = "${AMMONIT_OR_PASSWORD}"
        EOF
          chmod 600 ~/.config/ews/config/ammonit-or.toml
          echo "âœ… Created ~/.config/ews/config/ammonit-or.toml"
        else
          echo "â„¹ï¸  No Ammonit OR password available, skipping config creation"
        fi
        
        # Windcube Insights password (from repository secret WINDCUBE_INSIGHTS_PASSWORD)
        if [ -n "${WINDCUBE_INSIGHTS_PASSWORD:-}" ]; then
          cat > ~/.config/ews/config/windcube-insights.toml <<EOF
        [windcube-insights]
        email = "wm@ews-consulting.at"
        password = "${WINDCUBE_INSIGHTS_PASSWORD}"
        EOF
          chmod 600 ~/.config/ews/config/windcube-insights.toml
          echo "âœ… Created ~/.config/ews/config/windcube-insights.toml"
        else
          echo "â„¹ï¸  No Windcube Insights password available, skipping config creation"
        fi

        # Compatibility with old tests (we transitioned to ~/.config/ews/config like /etc/ews/config)
        if ls ~/.config/ews/config/*.toml 1> /dev/null 2>&1; then
          cp ~/.config/ews/config/*.toml ~/.config/ews/
        fi

    - name: Setup GitLab Package Registry
      uses: EWS-Consulting-Public/setup-uv-gitlab-registry-action@v1
      with:
        token: ${{ inputs.gitlab-token }}
        project-id: ${{ inputs.gitlab-project-id }}

    - name: Install dependencies
      if: inputs.install-dependencies == 'true'
      shell: bash
      run: |
        if [ -f uv.lock ]; then
          echo "ðŸ“¦ Using committed uv.lock"
          uv sync --frozen --all-extras
        else
          echo "ðŸ“¦ No uv.lock found, generating..."
          uv sync --all-extras
        fi
