# CI Workflow - Basic Package

name: CI

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: EWS-Consulting-Public/ews-ci-action/.github/workflows/ci.yml@v1
    with:
      python-versions: '["3.12", "3.13"]'  # Matrix testing
      lint-python-version: "3.12"
      run-coverage: true  # Upload to Codecov
      use-nox-build: true  # Use nox for build
    secrets: inherit
